//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookKeeping_Salary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookKeeping_Salary()
        {
            this.BookKeeping_Main = new HashSet<BookKeeping_Main>();
        }
    
        public int BookKeeping_Salary_Id { get; set; }
        public string BookKeeping_Salary_Number { get; set; }
        public string BookKeeping_Salary_Surname { get; set; }
        public string BookKeeping_Salary_Name { get; set; }
        public string BookKeeping_Salary_Patronymic { get; set; }
        public string BookKeeping_Salary_Salary_Rate { get; set; }
        public string BookKeeping_Salary_Work_Day { get; set; }
        public string BookKeeping_Salary_Total { get; set; }

        public string Number
        {
            get
            {
                return "Индф. номер: " + this.BookKeeping_Salary_Number;
            }
        }
        public string Surname
        {
            get
            {
                return "Фамилия: " + this.BookKeeping_Salary_Surname;
            }
        }
        public string Name
        {
            get
            {
                return "Имя: " + this.BookKeeping_Salary_Name;
            }
        }
        public string Patronymic
        {
            get
            {
                return "Отчество: " + this.BookKeeping_Salary_Patronymic;
            }
        }
        public string Rate
        {
            get
            {
                return "Оклад: " + this.BookKeeping_Salary_Salary_Rate + " руб.";
            }
        }
        public string Day
        {
            get
            {
                return "Кол-во рабочих дней: " + this.BookKeeping_Salary_Work_Day;
            }
        }
        public string Total
        {
            get
            {
                return "Итог: " + this.BookKeeping_Salary_Total + " руб.";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookKeeping_Main> BookKeeping_Main { get; set; }
    }
}
