//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookKeeping_User
    {
        public int BookKeeping_User_Id { get; set; }
        public string BookKeeping_User_Login { get; set; }
        public string BookKeeping_User_Password { get; set; }
    }
}
