//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookKeeping_Main
    {
        public int BookKeeping_Main_Id { get; set; }
        public Nullable<int> BookKeeping_User_Id { get; set; }
        public Nullable<int> BookKeeping_Salary_Id { get; set; }
        public Nullable<int> BookKeeping_Date_Id { get; set; }
        public Nullable<int> BookKeeping_Purchase_Id { get; set; }
        public Nullable<int> BookKeeping_Sale_Id { get; set; }
    
        public virtual BookKeeping_Date BookKeeping_Date { get; set; }
        public virtual BookKeeping_Purchase BookKeeping_Purchase { get; set; }
        public virtual BookKeeping_Salary BookKeeping_Salary { get; set; }
        public virtual BookKeeping_Sale BookKeeping_Sale { get; set; }
    }
}
