//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookKeeping_Date
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookKeeping_Date()
        {
            this.BookKeeping_Main = new HashSet<BookKeeping_Main>();
        }
    
        public int BookKeeping_Date_Id { get; set; }
        public string BookKeeping_Date_Number { get; set; }
        public string BookKeeping_Date_Salary { get; set; }
        public string BookKeeping_Date_Total { get; set; }

        public string Number
        {
            get
            {
                return "Индф.номер: " + this.BookKeeping_Date_Number;
            }
        }
        public string Salary
        {
            get
            {
                return "Дата след. з.п.: " + this.BookKeeping_Date_Salary;
            }
        }
        public string Total
        {
            get
            {
                return "Итоговая заработная плата: " + this.BookKeeping_Date_Total;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookKeeping_Main> BookKeeping_Main { get; set; }
    }
}
