//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKeeping
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookKeeping_Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookKeeping_Purchase()
        {
            this.BookKeeping_Main = new HashSet<BookKeeping_Main>();
        }
    
        public int BookKeeping_Purchase_Id { get; set; }
        public string BookKeeping_Purchase_Article { get; set; }
        public string BookKeeping_Purchase_Date { get; set; }
        public string BookKeeping_Purchase_Stock { get; set; }
        public string BookKeeping_Purchase_Total { get; set; }

        public string P_Article
        {
            get
            {
                return "Артикуль: " + this.BookKeeping_Purchase_Article;
            }
        }
        public string P_Date
        {
            get
            {
                return "Дата покупки: " + this.BookKeeping_Purchase_Date;
            }
        }
        public string P_Stock
        {
            get
            {
                return "Место покупки (Наим.организации): " + this.BookKeeping_Purchase_Stock;
            }
        }
        public string P_Total
        {
            get
            {
                return "Затраты: " + this.BookKeeping_Purchase_Total;
            }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookKeeping_Main> BookKeeping_Main { get; set; }
    }
}
